steps:
  - block: "Run the non-Bazel pipeline"
  - label: ":zzz: Trigger the non-Bazel pipeline"
    trigger: bazel-lunch-and-learn-non-bazel

  - block: "Run the Bazel pipeline"
  - label: ":bazel: Trigger the Bazel pipeline"
    trigger: bazel-lunch-and-learn-bazel
