## Bazel Quiz Pipeline
## Interactive multiple choice quiz to test Bazel knowledge

steps:
  - label: ":question: Welcome to the Bazel Quiz"
    command: |
      cat <<EOF | buildkite-agent annotate --style info --context welcome
      # 🎯 Bazel Knowledge Quiz

      Test your Bazel skills with 5 multiple choice questions!

      Each question will:
      1. Ask you to choose the correct Bazel command
      2. Run your choice to see if it works
      3. Show you the results

      Let's see how well you know Bazel!
      EOF

  - wait

  # Question 1
  - block: ":one: Question 1: Testing Targets"
    prompt: |
      How would you test all Go test targets?

      Command: bazel ___ "kind('.*_test', //...)"
    fields:
      - select: "Choose the correct Bazel command"
        key: "q1-answer"
        options:
          - label: "run"
            value: "run"
          - label: "test"
            value: "test"
          - label: "build"
            value: "build"
          - label: "query"
            value: "query"
        required: true

  - label: ":test_tube: Running your answer for Q1"
    command: |
      echo "--- Your answer: bazel $(buildkite-agent meta-data get q1-answer) \"kind('.*_test', //...)\""

      ANSWER=$(buildkite-agent meta-data get q1-answer)

      echo "Running: bazel $$ANSWER \"kind('.*_test', //...)\""
      bazel $$ANSWER "kind('.*_test', //...)" --test_output=errors

  - wait: ~

  # Question 2
  - block: ":two: Question 2: Running Binaries"
    prompt: |
      How would you execute the hello service?

      Command: bazel ___ //services/hello:hello
    fields:
      - select: "Choose the correct Bazel command"
        key: "q2-answer"
        options:
          - label: "test"
            value: "test"
          - label: "run"
            value: "run"
          - label: "build"
            value: "build"
          - label: "execute"
            value: "execute"
        required: true

  - label: ":rocket: Running your answer for Q2"
    command: |
      echo "--- Your answer: bazel $(buildkite-agent meta-data get q2-answer) //services/hello:hello"

      ANSWER=$(buildkite-agent meta-data get q2-answer)

      echo "Running: bazel $$ANSWER //services/hello:hello"
      bazel $$ANSWER //services/hello:hello

  - wait: ~

  # Question 3
  - block: ":three: Question 3: Finding Dependencies"
    prompt: |
      How would you find what the hello service depends on?

      Command: bazel query "_____(//services/hello:hello)"
    fields:
      - select: "Choose the correct query function"
        key: "q3-answer"
        options:
          - label: "deps"
            value: "deps"
          - label: "rdeps"
            value: "rdeps"
          - label: "kind"
            value: "kind"
          - label: "attr"
            value: "attr"
        required: true

  - label: ":mag: Running your answer for Q3"
    command: |
      echo "--- Your answer: bazel query \"$(buildkite-agent meta-data get q3-answer)(//services/hello:hello)\""

      ANSWER=$(buildkite-agent meta-data get q3-answer)

      echo "Running: bazel $$ANSWER \"deps(//services/hello:hello)\""
      bazel $$ANSWER "deps(//services/hello:hello)"

  - wait: ~

  # Question 4
  - block: ":four: Question 4: Impact Analysis"
    prompt: |
      If you change lib/utils, how do you find what's affected?

      Command: bazel query "_____(//..., //lib/utils:utils)"
    fields:
      - select: "Choose the correct query function"
        key: "q4-answer"
        options:
          - label: "deps"
            value: "deps"
          - label: "rdeps"
            value: "rdeps"
          - label: "allpaths"
            value: "allpaths"
          - label: "somepath"
            value: "somepath"
        required: true

  - label: ":chart_with_upwards_trend: Running your answer for Q4"
    command: |
      echo "--- Your answer: bazel query \"$(buildkite-agent meta-data get q4-answer)(//..., //lib/utils:utils)\""

      ANSWER=$(buildkite-agent meta-data get q4-answer)

      echo "Running: bazel $$ANSWER \"deps(//lib/utils:utils)\""
      bazel $$ANSWER "deps(//lib/utils:utils)"

  - wait: ~

  # Question 5
  - block: ":five: Question 5: Selective Testing"
    prompt: |
      How do you find ONLY the tests affected by changes to lib/utils?

      Command: bazel query "kind('.*_test', _____(//..., //lib/utils:utils))"
    fields:
      - select: "Choose the correct query function"
        key: "q5-answer"
        options:
          - label: "deps"
            value: "deps"
          - label: "rdeps"
            value: "rdeps"
          - label: "tests"
            value: "tests"
          - label: "filter"
            value: "filter"
        required: true

  - label: ":dart: Running your answer for Q5"
    command: |
      echo "--- Your answer: bazel query \"kind('.*_test', $(buildkite-agent meta-data get q5-answer)(//..., //lib/utils:utils))\""

      ANSWER=$(buildkite-agent meta-data get q5-answer)

      echo "Running: bazel $$ANSWER \"kind('.*_test', rdeps(//..., //lib/utils:utils))\""
      bazel $$ANSWER "kind('.*_test', rdeps(//..., //lib/utils:utils))"

  - wait: ~

  # Final Results
  - label: ":trophy: Quiz Complete"
    command: |
      cat <<EOF | buildkite-agent annotate --style success --context results
      # 🎉 Quiz Complete!

      Check the annotations above to see how you did on each question.

      ## Key Takeaways

      - \`bazel test\` - Run tests
      - \`bazel run\` - Build and execute binaries
      - \`bazel build\` - Build targets
      - \`bazel query\` - Explore the build graph

      ## Query Functions

      - \`deps(target)\` - What does this target depend on?
      - \`rdeps(scope, target)\` - What depends on this target? (impact analysis)
      - \`kind(pattern, scope)\` - Filter targets by type (e.g., tests, binaries)

      ## Smart CI/CD Pattern

      \`\`\`bash
      # Find affected tests
      AFFECTED=\$$(bazel query "kind('.*_test', rdeps(//..., //lib/utils:utils))")

      # Only run those tests
      bazel test \$$AFFECTED
      \`\`\`

      This is how Bazel enables intelligent, fast CI/CD pipelines!

      ---

      Want to learn more? Check out the interactive tutor: \`./tutor\`
      EOF
