steps:
  - label: ":golang: Test Utils Library"
    command: |
      cd lib/utils
      go test -v ./...

  - label: ":golang: Test Hello Service"
    command: |
      cd services/hello
      go test -v ./...

  - label: ":golang: Test Goodbye Service"
    command: |
      cd services/goodbye
      go test -v ./...

  - wait: ~

  - label: ":package: Build Hello Service"
    command: |
      cd services/hello
      go build -o hello
      ./hello

  - label: ":package: Build Goodbye Service"
    command: |
      cd services/goodbye
      go build -o goodbye
      ./goodbye

  - wait: ~

  - label: ":memo: Summary"
    command: |
      cat <<EOF | buildkite-agent annotate --style warning
      ## Traditional Build: What Just Happened?

      ❌ **Tested everything** - even if only one file changed
      ❌ **No caching** - every build starts from scratch
      ❌ **Manual steps** - added a new service? Update this pipeline!
      ❌ **No dependency intelligence** - can't determine what's affected by changes

      ---
      **Compare with \`pipeline.bazel.yaml\` to see the difference!**
      EOF
